In [ ]:
num = input("Enter string:")
pal = num[::-1]
print(pal)
if pal == num:
  print(f"{num} is a palindrome")
else:
  print(f"{num} is not a palindrome")

Enter string:121
121
121 is a palindrome


In [ ]:
li = [7,12,10,2,5]
li = sorted(li,reverse = True)
print(f"array after sorting is {li}")

array after sorting is [12, 10, 7, 5, 2]


In [ ]:
stri = input("Enter string:")
stri1 = stri[::-1]
print(f"string after getting reversed is {stri1}")

Enter string:Hello World!
string after getting reversed is !dlroW olleH


In [ ]:
bin1 = "011"
bin2 = "10"
bin1 = int(bin1,2)
bin2 = int(bin2,2)
tot = bin1+bin2
tot = bin(tot)
print(tot)

0b101


In [ ]:
ar1 = [3,6,5]
ar2 = [10,8,4,9,1,2,7]
ar = ar1+ar2
ar = sorted(ar)
print(f"array after sorting is {ar}")

array after sorting is [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
lo = [3,5,1,2,3,1]

seen=[]
dupli = []

for i in lo:
  if i in seen:
    dupli.append(i)
  else:
    seen.append(i)
print("Duplicate values are",dupli)

Duplicate values are [3, 1]


In [ ]:
import numpy as np

In [ ]:
sum = 0
lj = [[9,8,7],[5,4,6],[1,2,3]]
for i in range(len(lj)):
  sum = lj[i][i]+sum
print(f"sum of diagonal elements are",{sum})


sum of diagonal elements are {16}


In [ ]:
gh =  int(input("enter number:"))
rt = gh
gh1 = np.sqrt(gh)
print(gh1)
if rt%gh1 == 0:
  print(f"{gh1} is a perfect square root number")
else:
  print(f"{gh1} is not a perfect square number")

enter number:123
11.090536506409418
11.090536506409418 is not a perfect square number


In [ ]:
yu = input("enter string:")
chg = {}
for cht in yu:
  if cht in chg:
    chg[cht] += 1
  else:
    chg[cht] = 1

for chg,frequency in chg.items():
  print(f"{chg} - {frequency}")



enter string:madurai
m - 1
a - 2
d - 1
u - 1
r - 1
i - 1


In [ ]:
jg = int(input("enter number:"))
if jg > 1:
  for k in range(2,jg):
    if jg%k == 0:
      print(f"{jg} is not a prime number")
      break
  else:
    print(f"{jg} is a prime number")
else:
  print(f"{jg} is  not a prime number")


enter number:50
50 is not a prime number


In [ ]:
n1 = 1
n2 = 4
print(n1)
print(n2)
for i in range(5):
  next_term = n1+n2
  print(next_term)

  n1,n2 = n2,next_term

1
4
5
9
14
23
37


In [ ]:
stw = input("enter string:")
d = ['a','e','i','o','u','A','E','I','O','U']
for h in stw:
  if h in d:
    print(f"{stw} contains vowels in it")
    break
  else:
    print(f"{stw} doesnt contains vowels in the string")

enter string:input
input contains vowels in it


In [ ]:
stw1 = input("enter str:")
stw1 = stw1.split()
stw1 = stw1[-1]
print(f"Length of last word,'{stw1}' is {len(stw1)}")

enter str:hello world
Length of last word,'world' is 5


In [ ]:
gf = [6,5,4,3,1,8,2]
gf = sorted(gf)
i = int(input("enter number:"))
print(f"{i} (nth) largest value is {gf[i]}")

enter number:4
4 (nth) largest value is 5


In [ ]:
mul = bin1*bin2
mul = bin(mul)
print(f"Multiplied value:{mul}")

Multiplied value:0b110


In [ ]:
bh = "1101"
defu = int(bh,2)
print(f"Decimal value: {defu}")

Decimal value: 13


In [ ]:
gl = input("enter string:")
res = ""
for u in gl:
  res = u+res
print(f"reversed string is {res}")

enter string:143
reversed string is 341


In [ ]:
for row in range(5):
  for col in range(5):
    if col == 0 or col == 4 or ((row == 0 or row == 4) and (col > 0 or col < 4)):
      print("*",end="")
    else:
      print(end = " ")
  print()

*****
*   *
*   *
*   *
*****


In [ ]:
nj = int(input("enter num:"))
nj1 = nj
sum1 = 0
for i in range(len(str(nj))):
  dig = nj1%10
  sum1 = sum1+dig**3
  nj1 = nj1//10
print(sum1)

if sum1 == nj:
  print(f"{nj} is an armstrong number")
else:
  print(f"{nj} is not an armstrong number")

enter num:153
153
153 is an armstrong number


In [ ]:
per = int(input("enter num:"))
sum1 = 0
for k in range(1,per):
  if per%k == 0:
    sum1 = sum1+k
print(sum1)

if sum1 == per:
  print(f"{per} is a perfect number")
else:
  print(f"{per} is not a perfect number")

enter num:6
6
6 is a perfect number


In [ ]:
ui = "()[]{}"
for j in len(str(ui)):
  if ui[j] == '(' and ui[j+1] == ')':
    print("string is in correct syntax")
    break
  else:
    print("string is not in correct syntax")

TypeError: 'int' object is not iterable

In [ ]:
jh = [8,10,7,23]
lo=[]
for i in jh:
  if i>1:
    for j in range(2,i):
      if i%j == 0:
        lo.append(0)
        break
    else:
      lo.append(1)
  else:
    lo.append(1)

print(lo)


[0, 0, 1, 1]


In [ ]:
for row in range(5,0,-1):
  for col in range(row):
    print("*",end=" ")
  print()
for row in range(5):
  for col in range(row+1):
    print("*",end = " ")
  print()

* * * * * 
* * * * 
* * * 
* * 
* 
* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
kr = input("enter str:")
lo = []
sum2 = 0
for i in kr:
  lo.append(int(i))
print(lo)
lo1 = lo[0]+lo[-1]
for j in lo[1:-1]:
  sum2 = sum2+j
print(lo1,sum2)
if lo1 == sum2:
  print("given number is a xylem number")
else:
  print("given number is not a xylem number")

enter str:12348
[1, 2, 3, 4, 8]
9 9
given number is a xylem number


In [ ]:
num = 26
decf = hex(num)
print(f"hexadecimal form:{decf}")

hexadecimal form:0x1a


In [ ]:
senc = input("enter string:")
lp = []
for g in senc:
  lp.append(g.lower())

print(lp)

if len(lp) == 26:
  print(f"{senc} is a pangram sentence")
else:
  print(f"{senc} is not a pangram sentence")

enter string:abcdefghijklmnopqrstuvwxyz
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
abcdefghijklmnopqrstuvwxyz is a pangram sentence


In [ ]:
art = [[1,2,3],[4,5,6],[17,16,15]]
art = np.transpose(art)
print(art)

[[ 1  4 17]
 [ 2  5 16]
 [ 3  6 15]]


In [ ]:
pip install num2words

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.3/143.3 kB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=d965ccc445969574d2e45698ffdbc8b17b5eda9bd10afbd6b4980bd8894afefd
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
Successfully built docopt


In [ ]:
from num2words import num2words
io = int(input("enter str:"))
io = num2words(io)
print(io)

enter str:12345
twelve thousand, three hundred and forty-five


In [ ]:
ar1 = [[1,3,4],[2,4,3],[3,4,5]]
ar1 =np.array(ar1)
ar2 = [[1,3,4],[2,4,3],[1,2,4]]
ar2 = np.array(ar2)
ar = ar1+ar2
ar3 = ar1-ar2
print(ar)

[[2 6 8]
 [4 8 6]
 [4 6 9]]


In [ ]:
print(ar3)

[[0 0 0]
 [0 0 0]
 [2 2 1]]


In [ ]:
str1 = input("enter str:")
str2 = input("enter str:")
if sorted(str1) ==  sorted(str2):
  print(f"{str1} and {str2} are anagrams")
else:
  print(f"{str1} and {str2} are not anagrams")

enter str:mam
enter str:mam
mam and mam are anagrams


In [ ]:
stei = input("str:")
stei = stei.title()
print(f"Result:{stei}")

str:the quick brown fox
Result:The Quick Brown Fox


In [ ]:
stq = 'abcdef'
stw = 'defghi'
on = []
tw = []
th = []
for i in stq:
  on.append(i)
for j in stw:
  tw.append(j)

for k in on:
  if k in tw:
    th.append(k)

print(f"matching characters:{th}")

matching characters:['d', 'e', 'f']


In [ ]:
for rw in range(7):
  for col in range(rw+1):
    if rw%2 == 0:
      print(0,end = " ")
    else:
      print(1,end = " ")
  print()

0 
1 1 
0 0 0 
1 1 1 1 
0 0 0 0 0 
1 1 1 1 1 1 
0 0 0 0 0 0 0 


In [ ]:
sew = input("enter string:")
seen= []
dupo = []
for i in sew:
  if i in seen:
    dupo.append(i)
  else:
    seen.append(i)

for j in dupo:
  if j in seen:
    seen.remove(j)
print(dupo)
print(seen)

print(f"First non duplicate value : {seen[0]}")
print(f"Last non duplicate value: {seen[-1]}")


enter string:vaadi cute pottai
['a', ' ', 't', 't', 'a', 'i']
['v', 'd', 'c', 'u', 'e', 'p', 'o']
First non duplicate value : v
Last non duplicate value: o


In [ ]:
code = input("enter string:")
for row in range(len(code),0,-1):
  for col in range(row):
    print(code[col],end=" ")
  print()




enter string:54321
5 4 3 2 1 
5 4 3 2 
5 4 3 
5 4 
5 


In [ ]:
lp = [4,0,5,7,4]
jo = []
li = []

# Finding odd values in lp
for i in lp:
    if i != 0 and i % 2 != 0:
        li.append(i)

# If there are odd values in li, replace 0's in lp with the maximum odd value
if li:
    for p in range(len(lp)):
        if lp[p] == 0:
            lp[p] = max(li)

print("Output after finding maximum odd value in list:", lp)


Output after finding maximum odd value in list: [4, 7, 5, 7, 4]


In [ ]:
jn = [1,3,2,6,1]
ser = []
for i  in jn:
  if i in ser:
    ser.append(0)
  else:
    ser.append(i)
print(f"Resulting array : {ser}")

Resulting array : [1, 3, 2, 6, 0]


In [ ]:
jb = input("enter string:")
num = int(input("enter string"))
first = jb[num:]
second = jb[0:num]
tot = first+second
print(tot)

enter string:I'm a Fresher
enter string-2
erI'm a Fresh


In [ ]:
jh = [[7,8,9],[4,5,6],[1,2,3]]
swap1 = int(input("enter one:"))
swap2 = int(input("enter two:"))
a = jh[swap1]
jh[swap1] = jh[swap2]
jh[swap2] = a
print(jh)

enter one:0
enter two:2
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
ae = [[1,2,3],[4,5,6],[15,16,17]]
import numpy as np
ae = np.array(ae)
min = np.max(ae)
max = np.min(ae)
seu = np.sum(ae)
avg = np.average(ae)
print(f"min:{max},max:{min},sum:{seu},average:{avg}")

min:1,max:17,sum:69,average:7.666666666666667


In [ ]:
import numpy as np
pi = [[3,7,8],[9,11,13],[15,16,17]]
pi = np.array(pi)
minimum = np.amin(pi, axis = 1)
pi1 = np.transpose(pi)
maximum = np.amax(pi1, axis=1)
print(minimum)
print(maximum)
num = 0

for j in minimum:
  if j in maximum:
    num = num+j
    print(f"{num} is the lucky number")
    break
else:
  print(f"there us no lucky number in this matrix")


[ 3  9 15]
[15 16 17]
15 is the lucky number


In [ ]:
matrix = np.array([[1,0,0],[0,1,0],[0,0,1]])
numi = matrix.shape[0]
identity1 = np.identity(numi,dtype=matrix.dtype)
equal = np.array_equal(matrix,identity1)
if equal:
  print("The guven matrix is identity matrix")
else:
   print("The guven matrix is not an identity matrix")

The guven matrix is identity matrix


In [ ]:
stq = input("enter string:")
upper=[]
lower=[]
digit=[]
tot=[]

for i in stq:
  if i.isalpha() or i.isdigit():
    tot.append(i)

print(tot)

enter string:I Love You 3000
['I', 'L', 'o', 'v', 'e', 'Y', 'o', 'u', '3', '0', '0', '0']


In [ ]:
for j in tot:
  if j.isupper():
    upper.append(j)
  elif j.islower():
    lower.append(j)
  elif j.isdigit():
    digit.append(j)
print(upper)
upper1 = ((len(upper))/((len(tot)))) * 100
lower1 = ((len(lower))/((len(tot)))) * 100
digit1 = ((len(digit))/((len(tot)))) * 100

print(f"Uppercase - {len(upper)} ({upper1}%)")
print(f"Lowercase - {len(lower)} ({lower1}%)")
print(f"Digits - {len(digit)} ({digit1}%)")

['I', 'L', 'Y']
Uppercase - 3 (25.0%)
Lowercase - 5 (41.66666666666667%)
Digits - 4 (33.33333333333333%)


In [ ]:
inu = int(input("enter num:"))

while inu >= 10:
  su = 0
  for i in str(inu):
    su = su+int(i)

    inu = su

print(inu)

enter num:38
2


In [ ]:
# Initialize a list to store numbers with more than one same digit
jd = []

# Iterate over numbers from 101 to 200
for number in range(101, 201):
    # Convert number to string
    number_str = str(number)

    # Initialize a dictionary to store the count of each digit
    digit_count = {}

    # Iterate over each digit in the number
    for digit in number_str:
        # If the digit is already in the dictionary, increment its count
        if digit in digit_count:
            digit_count[digit] += 1
        # If the digit is not in the dictionary, initialize its count to 1
        else:
            digit_count[digit] = 1

    # Check if any digit occurs more than once
    digit_more_than_once = any(count > 1 for count in digit_count.values())

    # If any digit occurs more than once, add the number to the list
    if digit_more_than_once:
        jd.append(number)

# Print the list of numbers with more than one same digit
print("Numbers with more than one same digit:", jd)


Numbers with more than one same digit: [101, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 121, 122, 131, 133, 141, 144, 151, 155, 161, 166, 171, 177, 181, 188, 191, 199, 200]


In [ ]:
rh = []
su = 0
for i  in jd:
  ty = i
  while i > 0:
    di = i%10
    su = su+di
    i = i//10
    if  su <= 5:
      rh.append(ty)
      su = 0

print(rh)



[101, 101, 101, 110, 110, 110, 111, 111, 111, 112, 112, 112, 113, 113, 113, 114, 114, 114, 115, 115, 115]


In [ ]:
k = 5
for row in range(k,0,-1):
  for col in range(k):
    print(row , end = " ")
  print()
  k = k-1


5 5 5 5 5 
4 4 4 4 
3 3 3 
2 2 
1 


In [ ]:
from google.colab import files
up = files.upload()


Saving Orders.csv to Orders.csv


In [ ]:
!pip install pyspark

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.0/317.0 MB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pyspark: filename=pyspark-3.5.1-py2.py3-none-any.whl size=317488491 sha256=27f4b2823cb7c731bcc18a931624115b58e3efd6744090cb1e683dd45c2bc159
  Stored in directory: /root/.cache/pip/wheels/80/1d/60/2c256ed38dddce2fdd93be545214a63e02fbd8d74fb0b7f3a6
Successfully built pyspark


In [ ]:
import pyspark
from pyspark.sql import SparkSession

In [ ]:
spark = SparkSession.builder.appName('app').getOrCreate()

In [ ]:
type(spark)

pyspark.sql.session.SparkSession

In [ ]:
spark = spark.read.csv('Orders.csv',header = True,inferSchema = True)

In [ ]:
print(type(spark))
spark.show()

<class 'pyspark.sql.dataframe.DataFrame'>
+--------+------+------+--------+-----------+----------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|    Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+----------------+-----------+
| B-25681|  1096|   658|       7|Electronics|Electronic Games|        COD|
| B-26055|  5729|    64|      14|  Furniture|          Chairs|        EMI|
| B-25955|  2927|   146|       8|  Furniture|       Bookcases|        EMI|
| B-26093|  2847|   712|       8|Electronics|        Printers|Credit Card|
| B-25602|  2617|  1151|       4|Electronics|          Phones|Credit Card|
| B-25881|  2244|   247|       4|   Clothing|        Trousers|Credit Card|
| B-25696|   275|  -275|       4|   Clothing|           Saree|        COD|
| B-25687|   387|  -213|       5|   Clothing|           Saree|        UPI|
| B-25643|    50|   -44|       2|   Clothing|     Hankerchief|        UPI|
| B-25851|   135|   -54|       5|   Clothing|           Ku

In [ ]:
spark.head(3)


[Row(Order_ID='B-25681', Amount=1096, Profit=658, Quantity=7, Category='Electronics', Sub-Category='Electronic Games', PaymentMode='COD'),
 Row(Order_ID='B-26055', Amount=5729, Profit=64, Quantity=14, Category='Furniture', Sub-Category='Chairs', PaymentMode='EMI'),
 Row(Order_ID='B-25955', Amount=2927, Profit=146, Quantity=8, Category='Furniture', Sub-Category='Bookcases', PaymentMode='EMI')]

In [ ]:
spark.printSchema()

root
 |-- Order_ID: string (nullable = true)
 |-- Amount: integer (nullable = true)
 |-- Profit: integer (nullable = true)
 |-- Quantity: integer (nullable = true)
 |-- Category: string (nullable = true)
 |-- Sub-Category: string (nullable = true)
 |-- PaymentMode: string (nullable = true)



In [ ]:
spark['Amount']

Column<'Amount'>

In [ ]:
spark.dtypes

[('Order_ID', 'string'),
 ('Amount', 'int'),
 ('Profit', 'int'),
 ('Quantity', 'int'),
 ('Category', 'string'),
 ('Sub-Category', 'string'),
 ('PaymentMode', 'string')]

In [ ]:
spark.tail(3)

[Row(Order_ID='B-25973', Amount=4141, Profit=1698, Quantity=13, Category='Electronics', Sub-Category='Printers', PaymentMode='COD'),
 Row(Order_ID='B-25698', Amount=7, Profit=-2, Quantity=1, Category='Clothing', Sub-Category='Hankerchief', PaymentMode='COD'),
 Row(Order_ID='B-25993', Amount=4363, Profit=305, Quantity=5, Category='Furniture', Sub-Category='Tables', PaymentMode='EMI')]

In [ ]:
spark.describe().show()

+-------+--------+------------------+-----------------+-----------------+---------+------------+-----------+
|summary|Order_ID|            Amount|           Profit|         Quantity| Category|Sub-Category|PaymentMode|
+-------+--------+------------------+-----------------+-----------------+---------+------------+-----------+
|  count|    1500|              1500|             1500|             1500|     1500|        1500|       1500|
|   mean|    NULL| 291.8473333333333|           24.642|3.743333333333333|     NULL|        NULL|       NULL|
| stddev|    NULL|461.92462039764547|168.5588103631313|2.184941998447543|     NULL|        NULL|       NULL|
|    min| B-25601|                 4|            -1981|                1| Clothing| Accessories|        COD|
|    max| B-26100|              5729|             1864|               14|Furniture|    Trousers|        UPI|
+-------+--------+------------------+-----------------+-----------------+---------+------------+-----------+



In [ ]:
spark = spark.withColumn('Newcolumn',spark['Amount']+5)
spark.show()

+--------+------+------+--------+-----------+----------------+-----------+---------+
|Order_ID|Amount|Profit|Quantity|   Category|    Sub-Category|PaymentMode|Newcolumn|
+--------+------+------+--------+-----------+----------------+-----------+---------+
| B-25681|  1096|   658|       7|Electronics|Electronic Games|        COD|     1101|
| B-26055|  5729|    64|      14|  Furniture|          Chairs|        EMI|     5734|
| B-25955|  2927|   146|       8|  Furniture|       Bookcases|        EMI|     2932|
| B-26093|  2847|   712|       8|Electronics|        Printers|Credit Card|     2852|
| B-25602|  2617|  1151|       4|Electronics|          Phones|Credit Card|     2622|
| B-25881|  2244|   247|       4|   Clothing|        Trousers|Credit Card|     2249|
| B-25696|   275|  -275|       4|   Clothing|           Saree|        COD|      280|
| B-25687|   387|  -213|       5|   Clothing|           Saree|        UPI|      392|
| B-25643|    50|   -44|       2|   Clothing|     Hankerchief|   

In [ ]:
spark = spark.drop('Newcolumn')
spark.show()

+--------+------+------+--------+-----------+----------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|    Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+----------------+-----------+
| B-25681|  1096|   658|       7|Electronics|Electronic Games|        COD|
| B-26055|  5729|    64|      14|  Furniture|          Chairs|        EMI|
| B-25955|  2927|   146|       8|  Furniture|       Bookcases|        EMI|
| B-26093|  2847|   712|       8|Electronics|        Printers|Credit Card|
| B-25602|  2617|  1151|       4|Electronics|          Phones|Credit Card|
| B-25881|  2244|   247|       4|   Clothing|        Trousers|Credit Card|
| B-25696|   275|  -275|       4|   Clothing|           Saree|        COD|
| B-25687|   387|  -213|       5|   Clothing|           Saree|        UPI|
| B-25643|    50|   -44|       2|   Clothing|     Hankerchief|        UPI|
| B-25851|   135|   -54|       5|   Clothing|           Kurti|        COD|
| B-25703|   231|  -190| 

In [ ]:
spark.withColumnRenamed('Category','Cat').show()

+--------+------+------+--------+-----------+----------------+-----------+
|Order_ID|Amount|Profit|Quantity|        Cat|    Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+----------------+-----------+
| B-25681|  1096|   658|       7|Electronics|Electronic Games|        COD|
| B-26055|  5729|    64|      14|  Furniture|          Chairs|        EMI|
| B-25955|  2927|   146|       8|  Furniture|       Bookcases|        EMI|
| B-26093|  2847|   712|       8|Electronics|        Printers|Credit Card|
| B-25602|  2617|  1151|       4|Electronics|          Phones|Credit Card|
| B-25881|  2244|   247|       4|   Clothing|        Trousers|Credit Card|
| B-25696|   275|  -275|       4|   Clothing|           Saree|        COD|
| B-25687|   387|  -213|       5|   Clothing|           Saree|        UPI|
| B-25643|    50|   -44|       2|   Clothing|     Hankerchief|        UPI|
| B-25851|   135|   -54|       5|   Clothing|           Kurti|        COD|
| B-25703|   231|  -190| 

In [ ]:
spark.show()

+--------+------+------+--------+-----------+----------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|    Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+----------------+-----------+
| B-25681|  1096|   658|       7|Electronics|Electronic Games|        COD|
| B-26055|  5729|    64|      14|  Furniture|          Chairs|        EMI|
| B-25955|  2927|   146|       8|  Furniture|       Bookcases|        EMI|
| B-26093|  2847|   712|       8|Electronics|        Printers|Credit Card|
| B-25602|  2617|  1151|       4|Electronics|          Phones|Credit Card|
| B-25881|  2244|   247|       4|   Clothing|        Trousers|Credit Card|
| B-25696|   275|  -275|       4|   Clothing|           Saree|        COD|
| B-25687|   387|  -213|       5|   Clothing|           Saree|        UPI|
| B-25643|    50|   -44|       2|   Clothing|     Hankerchief|        UPI|
| B-25851|   135|   -54|       5|   Clothing|           Kurti|        COD|
| B-25703|   231|  -190| 

In [ ]:
spark.na.drop().show()

+--------+------+------+--------+-----------+----------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|    Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+----------------+-----------+
| B-25681|  1096|   658|       7|Electronics|Electronic Games|        COD|
| B-26055|  5729|    64|      14|  Furniture|          Chairs|        EMI|
| B-25955|  2927|   146|       8|  Furniture|       Bookcases|        EMI|
| B-26093|  2847|   712|       8|Electronics|        Printers|Credit Card|
| B-25602|  2617|  1151|       4|Electronics|          Phones|Credit Card|
| B-25881|  2244|   247|       4|   Clothing|        Trousers|Credit Card|
| B-25696|   275|  -275|       4|   Clothing|           Saree|        COD|
| B-25687|   387|  -213|       5|   Clothing|           Saree|        UPI|
| B-25643|    50|   -44|       2|   Clothing|     Hankerchief|        UPI|
| B-25851|   135|   -54|       5|   Clothing|           Kurti|        COD|
| B-25703|   231|  -190| 

In [ ]:
spark.na.drop(how = 'all').show()

+--------+------+------+--------+-----------+----------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|    Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+----------------+-----------+
| B-25681|  1096|   658|       7|Electronics|Electronic Games|        COD|
| B-26055|  5729|    64|      14|  Furniture|          Chairs|        EMI|
| B-25955|  2927|   146|       8|  Furniture|       Bookcases|        EMI|
| B-26093|  2847|   712|       8|Electronics|        Printers|Credit Card|
| B-25602|  2617|  1151|       4|Electronics|          Phones|Credit Card|
| B-25881|  2244|   247|       4|   Clothing|        Trousers|Credit Card|
| B-25696|   275|  -275|       4|   Clothing|           Saree|        COD|
| B-25687|   387|  -213|       5|   Clothing|           Saree|        UPI|
| B-25643|    50|   -44|       2|   Clothing|     Hankerchief|        UPI|
| B-25851|   135|   -54|       5|   Clothing|           Kurti|        COD|
| B-25703|   231|  -190| 

In [ ]:
spark.na.drop(how = 'any',subset = ['Amount','Category','Order_ID']).show()

+--------+------+------+--------+-----------+----------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|    Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+----------------+-----------+
| B-25681|  1096|   658|       7|Electronics|Electronic Games|        COD|
| B-26055|  5729|    64|      14|  Furniture|          Chairs|        EMI|
| B-25955|  2927|   146|       8|  Furniture|       Bookcases|        EMI|
| B-26093|  2847|   712|       8|Electronics|        Printers|Credit Card|
| B-25602|  2617|  1151|       4|Electronics|          Phones|Credit Card|
| B-25881|  2244|   247|       4|   Clothing|        Trousers|Credit Card|
| B-25696|   275|  -275|       4|   Clothing|           Saree|        COD|
| B-25687|   387|  -213|       5|   Clothing|           Saree|        UPI|
| B-25643|    50|   -44|       2|   Clothing|     Hankerchief|        UPI|
| B-25851|   135|   -54|       5|   Clothing|           Kurti|        COD|
| B-25703|   231|  -190| 

In [ ]:
spark.na.fill('missing values').show()

+--------+------+------+--------+-----------+----------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|    Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+----------------+-----------+
| B-25681|  1096|   658|       7|Electronics|Electronic Games|        COD|
| B-26055|  5729|    64|      14|  Furniture|          Chairs|        EMI|
| B-25955|  2927|   146|       8|  Furniture|       Bookcases|        EMI|
| B-26093|  2847|   712|       8|Electronics|        Printers|Credit Card|
| B-25602|  2617|  1151|       4|Electronics|          Phones|Credit Card|
| B-25881|  2244|   247|       4|   Clothing|        Trousers|Credit Card|
| B-25696|   275|  -275|       4|   Clothing|           Saree|        COD|
| B-25687|   387|  -213|       5|   Clothing|           Saree|        UPI|
| B-25643|    50|   -44|       2|   Clothing|     Hankerchief|        UPI|
| B-25851|   135|   -54|       5|   Clothing|           Kurti|        COD|
| B-25703|   231|  -190| 

In [ ]:
spark.na.fill(0,subset = ['Amount','Order_ID','Category']).show()

+--------+------+------+--------+-----------+----------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|    Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+----------------+-----------+
| B-25681|  1096|   658|       7|Electronics|Electronic Games|        COD|
| B-26055|  5729|    64|      14|  Furniture|          Chairs|        EMI|
| B-25955|  2927|   146|       8|  Furniture|       Bookcases|        EMI|
| B-26093|  2847|   712|       8|Electronics|        Printers|Credit Card|
| B-25602|  2617|  1151|       4|Electronics|          Phones|Credit Card|
| B-25881|  2244|   247|       4|   Clothing|        Trousers|Credit Card|
| B-25696|   275|  -275|       4|   Clothing|           Saree|        COD|
| B-25687|   387|  -213|       5|   Clothing|           Saree|        UPI|
| B-25643|    50|   -44|       2|   Clothing|     Hankerchief|        UPI|
| B-25851|   135|   -54|       5|   Clothing|           Kurti|        COD|
| B-25703|   231|  -190| 

In [ ]:
spark.select('Amount','Category').show()

+------+-----------+
|Amount|   Category|
+------+-----------+
|  1096|Electronics|
|  5729|  Furniture|
|  2927|  Furniture|
|  2847|Electronics|
|  2617|Electronics|
|  2244|   Clothing|
|   275|   Clothing|
|   387|   Clothing|
|    50|   Clothing|
|   135|   Clothing|
|   231|   Clothing|
|  2125|Electronics|
|  3873|Electronics|
|   729|  Furniture|
|  2188|  Furniture|
|     6|   Clothing|
|  1854|  Furniture|
|     6|   Clothing|
|  2093|  Furniture|
|     7|   Clothing|
+------+-----------+
only showing top 20 rows



In [ ]:
from pyspark.ml.feature import Imputer

imp = Imputer(inputCol = ['Amount','Profit','Quantity'],outputCol = [for c in ['Amount','Profit','Quantity']]
              ).setStrategy('Mean')

SyntaxError: invalid syntax (<ipython-input-42-ebce50a60b21>, line 3)

In [ ]:
spark.filter('Amount > 4000').show()

+--------+------+------+--------+-----------+------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+------------+-----------+
| B-26055|  5729|    64|      14|  Furniture|      Chairs|        EMI|
| B-25973|  4141|  1698|      13|Electronics|    Printers|        COD|
| B-25993|  4363|   305|       5|  Furniture|      Tables|        EMI|
+--------+------+------+--------+-----------+------------+-----------+



In [ ]:
spark.filter(spark['Amount'] > 4500).show()

+--------+------+------+--------+---------+------------+-----------+
|Order_ID|Amount|Profit|Quantity| Category|Sub-Category|PaymentMode|
+--------+------+------+--------+---------+------------+-----------+
| B-26055|  5729|    64|      14|Furniture|      Chairs|        EMI|
+--------+------+------+--------+---------+------------+-----------+



In [ ]:
spark.filter(spark['Category'] == 'Furniture').show()

+--------+------+------+--------+---------+------------+-----------+
|Order_ID|Amount|Profit|Quantity| Category|Sub-Category|PaymentMode|
+--------+------+------+--------+---------+------------+-----------+
| B-26055|  5729|    64|      14|Furniture|      Chairs|        EMI|
| B-25955|  2927|   146|       8|Furniture|   Bookcases|        EMI|
| B-25756|   729|  -492|       5|Furniture|   Bookcases|        UPI|
| B-25761|  2188|  1050|       5|Furniture|   Bookcases|Credit Card|
| B-25786|  1854|   433|       5|Furniture|   Bookcases|Credit Card|
| B-25853|  2093|   721|       5|Furniture|      Chairs|Credit Card|
| B-25910|  1622|  -624|       5|Furniture|      Tables|Credit Card|
| B-25686|  1829|   -56|       6|Furniture|      Tables|Credit Card|
| B-26048|  1461|   202|       5|Furniture|      Tables|        EMI|
| B-26003|  1745|   122|       2|Furniture|      Tables|Credit Card|
| B-25797|  1630|   802|       5|Furniture|      Tables|        EMI|
| B-25779|  1361|   980|       3|F

In [ ]:
spark.filter((spark['Amount'] > 3000) & (spark['Profit'] > 750)).show()

+--------+------+------+--------+-----------+------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+------------+-----------+
| B-25973|  4141|  1698|      13|Electronics|    Printers|        COD|
+--------+------+------+--------+-----------+------------+-----------+



In [ ]:
spark.filter((spark['Category'] == 'Furniture') | (spark['Amount'] > 3000)).show()

+--------+------+------+--------+-----------+------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+------------+-----------+
| B-26055|  5729|    64|      14|  Furniture|      Chairs|        EMI|
| B-25955|  2927|   146|       8|  Furniture|   Bookcases|        EMI|
| B-25923|  3873|  -891|       6|Electronics|      Phones|Credit Card|
| B-25756|   729|  -492|       5|  Furniture|   Bookcases|        UPI|
| B-25761|  2188|  1050|       5|  Furniture|   Bookcases|Credit Card|
| B-25786|  1854|   433|       5|  Furniture|   Bookcases|Credit Card|
| B-25853|  2093|   721|       5|  Furniture|      Chairs|Credit Card|
| B-25910|  1622|  -624|       5|  Furniture|      Tables|Credit Card|
| B-25686|  1829|   -56|       6|  Furniture|      Tables|Credit Card|
| B-26048|  1461|   202|       5|  Furniture|      Tables|        EMI|
| B-26003|  1745|   122|       2|  Furniture|      Tables|Credit Card|
| B-25

In [ ]:
spark.filter(~(spark['Quantity'] < 13)).show()

+--------+------+------+--------+-----------+------------+-----------+
|Order_ID|Amount|Profit|Quantity|   Category|Sub-Category|PaymentMode|
+--------+------+------+--------+-----------+------------+-----------+
| B-26055|  5729|    64|      14|  Furniture|      Chairs|        EMI|
| B-25640|  1499|   239|      13|   Clothing|       Saree|Credit Card|
| B-26019|   585|   175|      13|   Clothing|     T-shirt|        COD|
| B-26055|   213|     4|      14|   Clothing|       Shirt|        COD|
| B-25798|  2830| -1981|      13|  Furniture|   Bookcases|        EMI|
| B-25973|  4141|  1698|      13|Electronics|    Printers|        COD|
+--------+------+------+--------+-----------+------------+-----------+



In [ ]:
spark.groupby('Category').sum('Amount').show()

+-----------+-----------+
|   Category|sum(Amount)|
+-----------+-----------+
|Electronics|     166267|
|   Clothing|     144323|
|  Furniture|     127181|
+-----------+-----------+



In [ ]:
spark.agg({'Amount':'count'}).show()

+-------------+
|count(Amount)|
+-------------+
|         1500|
+-------------+



In [ ]:
# Note: To reflect the changes to a dataframe, assign it to a dataframe (equivalent to inplace in Pandas)